/***
Copyright 2020 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha

import (
	"context"
	time "time"

	dnswatchv1alpha "github.com/jojimt/dnswatch/pkg/crd/apis/dnswatch/v1alpha"
	versioned "github.com/jojimt/dnswatch/pkg/crd/clientset/versioned"
	internalinterfaces "github.com/jojimt/dnswatch/pkg/crd/informers/externalversions/internalinterfaces"
	v1alpha "github.com/jojimt/dnswatch/pkg/crd/listers/dnswatch/v1alpha"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClientViewInformer provides access to a shared informer and lister for
// ClientViews.
type ClientViewInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha.ClientViewLister
}

type clientViewInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewClientViewInformer constructs a new informer for ClientView type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClientViewInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClientViewInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredClientViewInformer constructs a new informer for ClientView type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClientViewInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DnswatchV1alpha().ClientViews(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DnswatchV1alpha().ClientViews(namespace).Watch(context.TODO(), options)
			},
		},
		&dnswatchv1alpha.ClientView{},
		resyncPeriod,
		indexers,
	)
}

func (f *clientViewInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClientViewInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clientViewInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&dnswatchv1alpha.ClientView{}, f.defaultInformer)
}

func (f *clientViewInformer) Lister() v1alpha.ClientViewLister {
	return v1alpha.NewClientViewLister(f.Informer().GetIndexer())
}
