/***
Copyright 2020 Cisco Systems Inc. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha "github.com/jojimt/dnswatch/pkg/crd/apis/dnswatch/v1alpha"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClientViews implements ClientViewInterface
type FakeClientViews struct {
	Fake *FakeDnswatchV1alpha
	ns   string
}

var clientviewsResource = schema.GroupVersionResource{Group: "dnswatch", Version: "v1alpha", Resource: "clientviews"}

var clientviewsKind = schema.GroupVersionKind{Group: "dnswatch", Version: "v1alpha", Kind: "ClientView"}

// Get takes name of the clientView, and returns the corresponding clientView object, and an error if there is any.
func (c *FakeClientViews) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha.ClientView, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clientviewsResource, c.ns, name), &v1alpha.ClientView{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.ClientView), err
}

// List takes label and field selectors, and returns the list of ClientViews that match those selectors.
func (c *FakeClientViews) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha.ClientViewList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clientviewsResource, clientviewsKind, c.ns, opts), &v1alpha.ClientViewList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha.ClientViewList{ListMeta: obj.(*v1alpha.ClientViewList).ListMeta}
	for _, item := range obj.(*v1alpha.ClientViewList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clientViews.
func (c *FakeClientViews) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clientviewsResource, c.ns, opts))

}

// Create takes the representation of a clientView and creates it.  Returns the server's representation of the clientView, and an error, if there is any.
func (c *FakeClientViews) Create(ctx context.Context, clientView *v1alpha.ClientView, opts v1.CreateOptions) (result *v1alpha.ClientView, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clientviewsResource, c.ns, clientView), &v1alpha.ClientView{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.ClientView), err
}

// Update takes the representation of a clientView and updates it. Returns the server's representation of the clientView, and an error, if there is any.
func (c *FakeClientViews) Update(ctx context.Context, clientView *v1alpha.ClientView, opts v1.UpdateOptions) (result *v1alpha.ClientView, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clientviewsResource, c.ns, clientView), &v1alpha.ClientView{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.ClientView), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClientViews) UpdateStatus(ctx context.Context, clientView *v1alpha.ClientView, opts v1.UpdateOptions) (*v1alpha.ClientView, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clientviewsResource, "status", c.ns, clientView), &v1alpha.ClientView{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.ClientView), err
}

// Delete takes name of the clientView and deletes it. Returns an error if one occurs.
func (c *FakeClientViews) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clientviewsResource, c.ns, name), &v1alpha.ClientView{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClientViews) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clientviewsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha.ClientViewList{})
	return err
}

// Patch applies the patch and returns the patched clientView.
func (c *FakeClientViews) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha.ClientView, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clientviewsResource, c.ns, name, pt, data, subresources...), &v1alpha.ClientView{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.ClientView), err
}
