apiVersion: v1
kind: ServiceAccount
metadata:
  name: dnswatcher
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnswatchrole
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "dnswatch.state"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dnswatcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dnswatchrole
subjects:
- kind: ServiceAccount
  name: dnswatcher
  namespace: kube-system

